### PR TITLE
Switch to pyproject.toml

### PR DESCRIPTION
**Pull request by adamjstewart**
This PR replaces the aging `setup.py` and `MANIFEST.in` with a modern `pyproject.toml`. For comparison, see [TorchGeo's pyproject.toml](https://github.com/microsoft/torchgeo/blob/main/pyproject.toml).

So far this includes no dependency changes. In my next PR I want to add tests for a range of dependency versions so we know which versions of timm are and aren't supported.

### CODE REVIEW

**Comment by adamjstewart** [comment]
NOTE: It's possible to dynamically read from `requirements.txt`, but in the future I'm planning on using `pyproject.toml` to list the actual range of dependencies and `requirements.txt` to list the latest tested version. So dependabot controls the latter, and the latter is used in CI, but the former is used for actually installing smp.

**Comment by qubvel** [comment]
Thanks for working on this! Looks good to me, the only question is how to safely manage both lists of requirements, isn't it better to have only one list with ranges to **test** and **install** the same versions? Maybe I'm missing something :)

**Comment by adamjstewart** [comment]
The idea with versions is that we _don't_ want the same versions for both test and install.

At install time, we want to support the widest range of versions possible. If a new version of timm comes out, we want people to be able to use it immediately. We don't want to force people to use one exact version, because if every library did that, nothing could be installed.

This comes at a cost. It becomes much harder to ensure that all of these versions are actually compatible. So at test time, we want to test both the minimum supported version, and the latest version. We keep these pinned to a specific version so that user PRs don't fail due to random changes in dependencies. Then, dependabot updates these pinned versions so that if something does break, it happens in a separate PR and is easy to debug and fix.

I'm not sure if I've ever seen a good article about this, this is mostly from experience. The first paragraph partly comes from:

* https://hynek.me/articles/semver-will-not-save-you/
* https://iscinumpy.dev/post/bound-version-constraints/

The second paragraph comes more from experience. For a long time, TorchGeo was the only library I knew that tested both minimum supported versions and the latest version. Since then, matplotlib has also been doing the same thing. The idea is very similar to testing a matrix of Python versions, except now we're also testing a matrix of dependencies too.

**Review by qubvel — APPROVED** [review]
Ok, thanks a lot for the explanation! Let's try this approach

**Comment by qubvel** [comment]
Btw, are you able to merge a PR now?

**Comment by adamjstewart** [comment]
It looks like I am!

**Pull request merged**
